### ISSUE TITLE
Null reference

### ISSUE THREAD

**Issue by songurov** [mrxten/XamEffects#29]
void BringLayer() {
            _layer.Layer.RemoveAllAnimations();
            _layer.Alpha = _alpha;
            View.BringSubviewToFront(_layer);
        }

**Comment by mrxten** [comment]
What concrete is null?

**Comment by mrxten** [comment]
and how you got this exception?

**Comment by Kornelis** [comment]
I guess the Issue is related to XF 4.0 and the Fast Renderes. I have a similar Issue with XF 4.0 (Android) when setting the TouchEffect on a Label as the Container Property of the PlatformEffect is null, so a NullRef Exception is thrown in the OnAttched Method. Not sure how this can be "workarounded".

**Comment by mrxten** [comment]
Yes, unfortunately effect doesn't work with fast renderers. Try wrap needed view with contentview

**Comment by mrxten** [comment]
Specified in readme.
