### ISSUE TITLE
TouchEffect triggers during scroll gesture

### ISSUE THREAD

**Issue by rbev** [mrxten/XamEffects#41]
Putting the toucheffect into an item within a scrollview/listview it will trigger the effect on touch-down, including during a scroll, rather than only when there is a touch-up in the same location (i.e. when the tapcommand executes)

I would expect it to ignore the tap in this scenario - it is quite confusing to an end user in any scrollable layout.

**Comment by mrxten** [comment]
For android I using ripple effect, it's usual behavior for android.
For ios I tried simulate touch effect from standard lists like from settings app. You can see, if you fast scrolling, effect wont push. If you will touch and keep finger some time, effect will appear and disappear when you scroll.

Sorry, I cannot implement your desire since in this case user wont understand that element touchable until touch-up. Effect should start when touch began, not after removing finger.
We cannot know where user touch-up and have to push effect. But I added some timer for avoid immediate appearing effect in ios, just for your case - if user will touch-down and will scroll immediately (in 200-500ms after starting touch) effect wont push.

I dont see any another way for work this effect in scroll.
